### ISSUE TITLE
Fps drop while using multipart cables 

### ISSUE THREAD

**Issue by gigabit101** [TechReborn/TechReborn_TODO#12]
Fps drop while using multipart cables

**Comment by modmuss50** [comment]
@amadornes said he was going to optimise the rendering. I will see if it is the rendering or something else.

**Comment by modmuss50** [comment]
When paused I get 1500FPS then when I go back into game this goes down to 900. So this is NOT a rendering issue.

**Comment by modmuss50** [comment]
Fixed, every cable had is own world! woops
