### ISSUE TITLE
Matter Fabricator

### ISSUE THREAD

**Issue by modmuss50** [TechReborn/TechReborn_TODO#16]
http://feed-the-beast.wikia.com/wiki/Matter_Fabricator

Makes uu slowly from power.

Can be made quicker with scrap.

**Comment by Carbon-Ghost** [comment]
Actually the GT version used to make UU with scrap being a requirement so unless you guys wants to change it, I just wanted to remind you this fact ;)

**Comment by modmuss50** [comment]
It takes a long time and a lot of power to make it with power alone

**Comment by Carbon-Ghost** [comment]
Well, in the old GT, matter fabricator required scrap to run, unlike the mass fabricator, you can test it if you want on FTB ultimate ;)

**Comment by modmuss50** [comment]
I beleive you, Its easy to fix if needed, I think @gigabit101 asked me to add it in

**Comment by gigabit101** [comment]
yes he is right I was thinking of the old mass fab just remove it

**Comment by modmuss50** [comment]
It will no longer run without power

**Comment by Carbon-Ghost** [comment]
Without power or scrap ? scrap right xD ?

**Comment by modmuss50** [comment]
without only power, bad wording :P
