### ISSUE TITLE
Add Semifluid Generator

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn_TODO#32]
Add the UI and functionality for the semifluid generator.
http://ftb.gamepedia.com/Semifluid_Generator

**Comment by joflashstudios** [comment]
@modmuss50 , design question:

Should the semifluid generator support newer fuels, such as IC2 biogass, forestry ethanol, or MFR biofuel like the IC2 version, or should it simply work with the old fuels defined in the link?

**Comment by modmuss50** [comment]
It should work with the new ones.
