### ISSUE TITLE
Add gas turbine

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn_TODO#33]
Add gas turbine.
http://ftb.gamepedia.com/Gas_Turbine_%28GregTech_4%29

**Comment by joflashstudios** [comment]
This might be out of scope, but I came across something interesting:

If we're looking at the Biogass Wikipedia page, it seems that Biogass would make more sense being burned in the Gas Turbine, instead of the semifluid generator. Doesn't matter a whole lot, but it's something to consider. Perhaps enable the burning of Biogas in a slightly more efficient manner if you burn it in a turbine instead of a semifluid generator? Biogas burning turbines are a real thing:

http://en.wikipedia.org/wiki/Biogas (note mention of turbines under "Production")
http://www.biogassystems.com/en/products/gas-turbines
http://www.capstoneturbine.com/prodsol/solutions/rrbiogas.asp

**Comment by gigabit101** [comment]
Is this done??

**Comment by joflashstudios** [comment]
Yeah, I added the gas turbine, it works, generates eu, etc.
