### ISSUE TITLE
Add fusion reactor

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn_TODO#35]

**Comment by Carbon-Ghost** [comment]
Small question, can we add back both the very old fusion reactor and the normal one ? I really want the old fusion reactor back as I think it was quite awsome, and did it job quite well. 

Basically, the small fusion reactor use will be for people having a lot of ressources, needing a lot of power in a renewable way for a medium-large size infrastructure/base. 

And the big one for huge bases / Cities with multiple players.

Also change a bit the crafts and how it works for balance : 
- Fusion reactor ( small one ) will require fusion reactor coils ( crafted with superconductor Cables, highly advanced machine blocks and other components ) in a "ring" shape with one of the blocks of the ring needing a fusion computer controller.
 
The fusion computer controller will look like the old fusion computer in GT2-3, with the front face having a monitor, back face having the energy output, all the other sides being able to be used for the energy input for starting the fusion reaction. 

Fusion computer will show a buffer of 100 000 000 EU, once the buffer is full, fusion will start if it detects fuel, and the buffer will get back to 0, but will not require to be restarted as long as there is fuel to sustain the reaction. It can still be recharged through the recharge sides to maximum while running and producing energy though even though it will be useless as the fusion reactor will first attempt to get it's buffer full before outputing energy.

 Now here's the deal with this fusion reactor, it will only be able to be used to produce energy, so people will need to get the other fusion reactor for generating ressources. Here are the possible fuel that can be used and the values they generate : 

1000 mB of Deuterium + 1000 mB of Deuterium = 100 eu/tick in 8192 packets and producing a total of 100 000 eu. 

1000 mB of Deuterium + 1000 mB of Tritium = 2048 eu/tick in 8192 packets and producing a total of 200 000 eu. 

1000 mB of Deuterium + 1000 mB of Helium-3 = 4096 eu/tick in 8192 packets and producing a total of 1 000 000 eu.

**Comment by Carbon-Ghost** [comment]
The big fusion reactor will be renamed into Advanced fusion reactor and everything should stay the same with 2 changes : 

- The Advanced Fusion reactor will generate by default EU using Energy extractor and not material extractors, but additionnally can have Material extractors to use plasma so it's more efficient, additionnally you can use photon receivers plating ( basically solar panels for the reactor ) instead of the advanced machine casing for generating a little extra EU, the photon receiver will require the advanced machine casings and some kind of solar panel like component to be crafted. 

The goal is to make the Advanced fusion reactor modular ( way more modular than the old GT one ) and better. 

Gonna post numbers and fusion products asap, still calculating them for balance purposes..

**Comment by modmuss50** [comment]
Its in!!!

**Comment by Carbon-Ghost** [comment]
OMG hype..

**Comment by modmuss50** [comment]
Its only the old one ATM. I most likely wont put the new one in.

**Comment by Carbon-Ghost** [comment]
don't ;D 
Also small question, I may do a small GT reborn specially for IC2 classic, for now the goal is to make a BF and Centrifuge mod for modpack makers for IC2 classic, but later I want to add more, may I use some code ?

**Comment by modmuss50** [comment]
As long as it fits with in the license. https://github.com/TechReborn/TechReborn/blob/master/LICENSE.md

**Comment by Carbon-Ghost** [comment]
May I have a TLDR of it ? I suck at politics, so from what I understand : 
- I shall not sell it or claim as mine, correct ?

**Comment by modmuss50** [comment]
It must be open source, and you must say where you got the original source from. And you must use the same licence we are using.

For example in every copied class in the header just say you got it from us, and on the download page link to us.

**Comment by Carbon-Ghost** [comment]
kk
