### ISSUE TITLE
Add connected textures to machine casings

### ISSUE THREAD

**Issue by joflashstudios** [TechReborn/TechReborn_TODO#45]

**Comment by modmuss50** [comment]
I dont know how to do this.

**Comment by joflashstudios** [comment]
Apparently the normal way to do this is super complicated: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2224214-creating-connected-textures-for-a-glass-block

However, you might be able to do something custom by overriding getIcon: http://www.minecraftforge.net/forum/index.php?topic=27907.0

**Comment by modmuss50** [comment]
Ok thanks :)

**Comment by modmuss50** [comment]
I may write something custom because the ways that you have shown me all need a crap load of different texture files.
