### ISSUE TITLE
Superconductor cables

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn_TODO#54]
Superconductor cables from Gregtech, like before they are lossless and can transport any packets of EU ( well MAX INT is the max ;) ) and will never get fried ^.^

3 small differences from GT : 
- This superconductor cable won't be a whole block large, and will be at the size of an HV max insulated cable because it looks better, or if you guys prefer finer, glass fiber size ^.^
-Texture slightly different
-Crafting recipe :  
SuperConductor insulators * 3 = 
Glass, Glass, Glass ;
Iridium reinforced plate, Iridium reinforced plate, Iridium reinforced plate ;
TechReborn best coolant cell, TechReborn best coolant cell, TechReborn best coolant cell 

Superconductor ceramic plate = 

  Superconductor blend = 1 gold dust, 1 redstone dust, 1 glowstone dust, 1 silicon dust
Then Blast furnace then plate bending machine

Then Super conductor frame * 3 = 
Ceramic plate, Glass fibre, Ceramic Plate ; 
Ceramic plate, Superconductor ( item ), Ceramic Plate ;
Ceramic plate, Glass fibre, Ceramic Plate

then Superconductor cable = 
Insulation, Insulation, Insulation ;
Frame, Frame, Frame ;
Insulation, Insulation, Insulation ;

Voila, submitting textures in just a moment, felt the crafting recipes needed to be complex due to the cable being OP and mainly made for the fusion reactor and overthrowing all the other cables, also don't yell at me "E-net is unfinished" please : http://forum.industrial-craft.net/index.php?page=Thread&threadID=11586&pageNo=1

**Comment by modmuss50** [comment]
Do you know if that mod works with the fmp cables?

**Comment by Carbon-Ghost** [comment]
Haven't tested yet, I don't think so, do you want me to bug Aroma and see if support can be implemented ?

**Comment by modmuss50** [comment]
It will be a thing that I will have to fix

**Comment by Carbon-Ghost** [comment]
Ah... On the plus side the cable texture is getting to somewhere, still trying to make it better :3
