### ISSUE TITLE
Greg approval and other important stuff !

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn_TODO#56]
I talked to Greg on the IC2 forums about this project, as he was unaware of it and wanted to know it ( as it's a remake of an older version of his mod ), after talking, he said he 100% approved our project, and reconfirmed that he was ok with us using his textures, at 1 condition, that I need to post the project on the IC2 forum on the GregTech part, so I did that, here it is : http://forum.industrial-craft.net/index.php?page=Thread&postID=190654#post190654

I am completing atm and adding pics :D 

Hope you are ok with what I did ^.^

**Comment by modmuss50** [comment]
2 things, Can we have a Q&A? and can you put our names, modmuss50, gigabit101, Tntrololol, joflashstudios, mattabase, johnodagiant

**Comment by Carbon-Ghost** [comment]
Working on it, a the moments I was trying to make a huge pic where all the good things could have been showed, but ofc I am gonna put the dev names ^^ 
@Q&A what should I put in it ?

**Comment by modmuss50** [comment]
Just say we will replay to the questions on the thread, I will keep checking it and answer them

**Comment by Carbon-Ghost** [comment]
Kk, also done ^^

Also, what is the current state of the mod ? Will we see a stable release soon ? We have a hype train going on...

**Comment by modmuss50** [comment]
An alpha is a while off

**Comment by Carbon-Ghost** [comment]
Oh kk, also once we get to beta/release, can we begin the IC2 classic compat thingy ?

**Comment by modmuss50** [comment]
Its working, just no recipes

**Comment by modmuss50** [comment]
Do you mind saying that we will answer questions?

**Comment by Carbon-Ghost** [comment]
Absolutely not ^^

**Comment by modmuss50** [comment]
why?

**Comment by Carbon-Ghost** [comment]
Okay just noticed I messed up my negative sentencing, what I mean is go ahead do want you want to do xD

**Comment by modmuss50** [comment]
ohhhh, I get it sorry :P haha my fault

**Comment by Carbon-Ghost** [comment]
Wait did I messed up my negative sentencing or not ? xD

**Comment by modmuss50** [comment]
@Carbon-Ghost we are now in alpha :) Could you update your post?

http://www.techreborn.ninja/home/

**Comment by Carbon-Ghost** [comment]
Done :)
