### ISSUE TITLE
Better textures

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn_TODO#58]
More user friendly centrifuge GUI finished : http://imgur.com/P89KYTE
Next : Better IDSU and AESU GUI
Next : Re-do some of the textures to make them better
Next : Re-do some of the textures to make them 32x like experimental

**Comment by Carbon-Ghost** [comment]
IDSU and AESU guis done, tell me once you are ready to use them, I will post them :)

**Comment by modmuss50** [comment]
I could do with them now :)

**Comment by Carbon-Ghost** [comment]
KK uploading :D

**Comment by Carbon-Ghost** [comment]
http://imgur.com/GGGgfZp,TBaiLjv,g28l7Ak#0

IDSU, AESU, LESU GUI textures, note that the middle slot in the AESU GUI is where you can set a value ranging from 1-2048 ( or 0-2048 if you want to allow users to have a capacitor for charging stuff without worrying about the output ).

**Comment by modmuss50** [comment]
Quick question, is that a high res texture?

**Comment by Carbon-Ghost** [comment]
No, not as far as I am aware, it's my old FTB ultimate pack slightly modified default texture pack ( for my eyes ) with a few tweaks iirc.

**Comment by modmuss50** [comment]
ok thanks, I might just be me, when I get the chance I will add it back in

**Comment by Carbon-Ghost** [comment]
Yeah, you mean the lighting bolt ... But I am pretty sure it's default, I never used faithful back then due to the fact that my old computer wasn't able to handle it iirc....
