### ISSUE TITLE
Custom E-net

### ISSUE THREAD

**Issue by Carbon-Ghost** [TechReborn/TechReborn_TODO#59]
We need a custom e-net to work if TechReborn is alone. 

Now if IC2 classic or exp is present, make the use of the custom E-net an option ( if enabled, the TechReborn cables will work, and IC2 ones will be uncrafteable ), if disabled, the instance will use normal IC2 cables and ( duh ) the normal E-net ( except for the superconductor added by Techreborn as IC2 e-net can't allow a superconducting cable ), should solve that issue at the same time ;)

**Comment by modmuss50** [comment]
The superconductive cable is useless.
The fact that we support RF is to use it with other mods, use a mod that adds RF cables.

**Comment by Carbon-Ghost** [comment]
What if I use techReborn alone ?

**Comment by Carbon-Ghost** [comment]
or with an non RF/EU ( aka electric or similar ) energy source mod ?

**Comment by Carbon-Ghost** [comment]
You could use GregTech 5 e-net, we can use it since we are considered as an unofficial but approved GT spinoff ( worst case I can still ask Greg the permission :D  )

**Comment by gigabit101** [comment]
you can generate are power inside of are mods but we are not adding cables to use with it

**Comment by Carbon-Ghost** [comment]
Why not ? Maybe think of it later as low priority, I would love to have 1 or 2 cables ( a basic one like aluminium and a superconductor one ) using GT5 e-net :3

**Comment by gigabit101** [comment]
we dont use or will ever use GT5s e-net we have are own also as far as cables go if we do decide to add something like that they will be in TechReborn-Addons

**Comment by Carbon-Ghost** [comment]
kk nice :D 

2 Small unrelated questions though : Have you decided in the end if you wanted to add a Black Hole like chest in Quantum storage ? Also I am working with 2 other people on AE - Reloaded ( name subject to change if we don't get the permission ), may it get a compat update for it's storage bus once it's out ?

**Comment by gigabit101** [comment]
do it your end just use the IdeepstorageApi then it will work with mine, mfrs and jabba

**Comment by Carbon-Ghost** [comment]
Oh nice :D Kk, noting that ^^
